# Generated by Django 5.2.8 on 2026-01-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
