# Generated by Django 5.2.8 on 2026-01-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dueDate', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='general', max_length=50)),
                ('priority', models.CharField(default='medium', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('caseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cases.case')),
            ],
        ),
    ]
