# Generated by Django 5.2.8 on 2026-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
