# Generated by Django 5.2.8 on 2026-01-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_casetype_remove_case_type_case_casetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='nic',
        ),
    ]
